"""Judge the whole catalog on the whole panel and write the report.

    python3 scripts/thing_judge.py            # report + catalog sheet
    python3 scripts/thing_judge.py --quick    # owners + extremes only

Writes docs/things/QUALITY.md (every item: cats checked, fails, warnings)
and docs/things/img/catalog.png (each item alone on a light and a dark
wallpaper, and in use by the default cat and an owner's cat). Exit code 1
if anything fails.
"""
import argparse
import sys
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
from PIL import Image, ImageDraw  # noqa: E402

from companion.creatures import api, panel  # noqa: E402
from companion.things import catalog, fit as F, judge, scene  # noqa: E402
from companion.things.kinds import KINDS  # noqa: E402

DOCS = ROOT / "docs" / "things"
LIGHT, DARK = (206, 222, 206, 255), (40, 44, 52, 255)


def cell(rgba, w, h, bg, z=3, size=(70, 54)):
    W, H = size
    im = Image.new("RGBA", (W, H), bg)
    im.alpha_composite(Image.frombytes("RGBA", (w, h), rgba), ((W - w) // 2, H - h - 1))
    return im.resize((W * z, H * z), Image.NEAREST)


def in_use(it, pet, ft):
    r = KINDS[it.kind].render(it.design, ft)
    if it.kind == "toy":
        return scene.carry(r, pet, "carrysit", 2)
    rgba, w, h, _ = scene.compose(r, pet, None, 2)
    return rgba, w, h


def alone(it, ft):
    r = KINDS[it.kind].render(it.design, ft)
    out = bytearray(r.w * r.h * 4)
    scene.over(out, r.w, r.h, r.back, r.w, r.h, 0, 0)
    if r.front:
        scene.over(out, r.w, r.h, r.front, r.w, r.h, 0, 0)
    return bytes(out), r.w, r.h


def main(argv=None):
    ap = argparse.ArgumentParser()
    ap.add_argument("--quick", action="store_true")
    args = ap.parse_args(argv)
    cats = panel.panel(("owners", "extremes") if args.quick else
                       ("owners", "extremes", "samples", "random"))
    t0 = time.time()
    reports = [judge.judge(it.kind, it.design, cats) for it in catalog.ITEMS]
    canon = api.Creature(api.canon_genome())
    cft = F.measure(canon)
    variety = judge.variety_gate([(it.name, KINDS[it.kind].render(it.design, cft))
                                  for it in catalog.ITEMS])
    ok = all(r.passed for r in reports) and not variety
    DOCS.mkdir(parents=True, exist_ok=True)
    lines = ["# Things: quality report", "",
             f"Generated by `scripts/thing_judge.py` on {len(cats)} panel cats "
             f"({time.time() - t0:.0f}s). **{'ALL PASS' if ok else 'FAILURES'}**.", "",
             "Gates: pixels (closed outline, no stray pixels, <= 12 colours), wallpapers "
             "(separates from light and dark), in use (per kind, every cat, both "
             "sides), variety (things of one kind differ by >= "
             f"{judge.VARIETY_DE:.0f} mean dE). Warnings are for the reviewer; the shop "
             "can use them (e.g. a bed close to your cat's colour).", "",
             "| Item | Kind | Price | Cats | Result | Warnings |", "|---|---|---|---|---|---|"]
    for it, r in zip(catalog.ITEMS, reports):
        warn = sorted({f.cat for f in r.findings if f.level == "warn"})
        wtxt = f"{len(warn)}: {', '.join(warn[:4])}{'…' if len(warn) > 4 else ''}" if warn else ""
        res = "✅" if r.passed else "❌ " + "; ".join(f"{f.cat}: {f.message}" for f in r.fails()[:3])
        lines.append(f"| {it.name} | {it.kind} | {it.price} | {r.cats} | {res} | {wtxt} |")
    if variety:
        lines += ["", "## Variety failures", ""] + [f"- {f.message}" for f in variety]
    lines += ["", "![catalog](img/catalog.png)", ""]
    (DOCS / "QUALITY.md").write_text("\n".join(lines), "utf-8")
    # the sheet: item alone (light, dark), with the default cat, with an owner's cat
    owner = panel.panel(("owners",))[1][1]
    opet = api.Creature(owner)
    oft = F.measure(opet)
    rows = []
    for it in catalog.ITEMS:
        a = alone(it, cft)
        cells = [cell(*a, LIGHT), cell(*a, DARK), cell(*in_use(it, canon, cft), LIGHT),
                 cell(*in_use(it, opet, oft), LIGHT)]
        rows.append((f"{it.name} ({it.price})", cells))
    cw, ch = rows[0][1][0].size
    img = Image.new("RGBA", (180 + cw * 4, ch * len(rows)), (255, 255, 255, 255))
    d = ImageDraw.Draw(img)
    for r, (label, cells) in enumerate(rows):
        d.text((4, r * ch + ch // 2 - 6), label, fill=(0, 0, 0, 255))
        for c, im in enumerate(cells):
            img.paste(im, (180 + c * cw, r * ch))
    (DOCS / "img").mkdir(exist_ok=True)
    img.save(DOCS / "img" / "catalog.png")
    print("\n".join(r.summary() for r in reports))
    for f in variety:
        print("VARIETY:", f.message)
    print("OK" if ok else "FAILED")
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
